<a href="https://colab.research.google.com/github/surajslab/NumpyBasics/blob/main/numpy_notes(Jovian).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reference :https://www.youtube.com/watch?v=d0E0_87CrFA&list=PLyMom0n-MBrpzC91Uo560S4VbsiLYtCwo&index=4

# **Numpy for Data Analysis and Machine Learning**

### Multidimensional Arrays

In [2]:
import numpy as np

### 2D Arrays

In [3]:
climate_data=np.array([
                       [1,2,3,4],
                       [5,6,7,8],
                       [9,10,11,12]
                       
                       
                       ])
climate_data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
climate_data.shape

(3, 4)

### 3D Arrays

In [5]:
climate_data=np.array([
                       [[1,2],[3,4]],
                       [[5,6],[7,8]],
                       [[9,10],[11,12]]
                       
                       
                       ])
climate_data

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [6]:
climate_data.shape

(3, 2, 2)

### Working with CSV Files

In [7]:
from  urllib.request import urlretrieve

In [8]:
url='https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv'

In [9]:
urlretrieve(url,"climate.txt")

('climate.txt', <http.client.HTTPMessage at 0x7f815a0a4990>)

In [10]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [11]:
climate_data.shape

(10000, 3)

### Performing a matrix multiplication with random weights to predict the yeilds of apple in a year.


In [12]:
weights=np.array([0.3,0.2,0.5])

In [13]:
climate_data.shape, weights.shape

((10000, 3), (3,))

### Since you can see the shape of climate data is 1000/3 and shape of weights is 3/1 thus the shape of resultant matrix is 10000,1 

In [14]:
yeilds = climate_data @ weights

In [15]:
yeilds

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

### Putting this yield data into the climate_data !!

In [16]:
climate_data=np.concatenate((climate_data,yeilds.reshape(10000,1)),axis=1)

In [17]:
climate_data

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [18]:
climate_data.shape

(10000, 4)

In [19]:
np.savetxt("climate_data.txt",
           climate_data,
           fmt="%.2f",
           header="temperature,rainfall,humidity,yield_apples")

Numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used functions:


* Mathematics: `np.sum`, `np.exp`, `np.round`, arithemtic operators 
* Array manipulation: `np.reshape`, `np.stack`, `np.concatenate`, `np.split`
* Linear Algebra: `np.matmul`, `np.dot`, `np.transpose`, `np.eigvals`
* Statistics: `np.mean`, `np.median`, `np.std`, `np.max`

 

> You can find a full list of array functions here: https://numpy.org/doc/stable/reference/routines.html

# **Arithmetic Operations and Broadcasting**
<br>

Numpy arrays support arithmetic operators like `+`, `-`, `*`, etc. You can perform an arithmetic operation with a single number (also called scalar) or with another array of the same shape. Operators make it easy to write mathematical expressions with multi-dimensional arrays.

In [20]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [21]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

Adding 2 arrays

In [22]:
arr2+arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

Adding a scalar

In [23]:
arr2+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11,  3,  4,  5]])

Element wise multiplication

In [24]:
arr2*arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [25]:
arr4=np.array([1,2,3,4])

When the expression `arr2 + arr4` is evaluated, `arr4` (which has the shape `(4,)`) is replicated three times to match the shape `(3, 4)` of `arr2`. Numpy performs the replication without actually creating three copies of the smaller dimension array, thus improving performance and using lower memory.

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width="360">

Broadcasting only works if one of the arrays can be replicated to match the other array's shape.

In [26]:
arr2+arr4

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10,  3,  5,  7]])

# **Array indexing and slicing**

Numpy extends Python's list indexing notation using `[]` to multiple dimensions in an intuitive fashion. You can provide a comma-separated list of indices or ranges to select a specific element or a subarray (also called a slice) from a Numpy array.

In [27]:
arr = np.array([
                
    [ [11, 12, 13, 14],  
     
     [13, 14, 15, 19] ], 
    
    
    [ [15, 16, 17, 21],  
     
     [63, 92, 36, 18] ], 
    

    [ [98, 32, 81, 23],   
     
     [17, 18, 19.5, 43]]
    
    ])

In [33]:
arr[0,0,0]

11.0

In [34]:
arr[1,1]

array([63., 92., 36., 18.])

In [35]:
arr[1,1,2]

36.0

### Mixing Arrays and Indexes

In [31]:
arr

array([[[11. , 12. , 13. , 14. ],
        [13. , 14. , 15. , 19. ]],

       [[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [36]:
arr[1:]

array([[[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [38]:
arr[1:,1]

array([[63. , 92. , 36. , 18. ],
       [17. , 18. , 19.5, 43. ]])

In [39]:
arr[1:,1,1:]

array([[92. , 36. , 18. ],
       [18. , 19.5, 43. ]])

# **Other Ways of Creating Numpy Arrays**

In [42]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
np.ones((3,2))

(3, 2)

In [50]:
np.ones([3,2,2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

Identity Matrix

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.random.rand(5)

array([0.38378402, 0.52844486, 0.82628861, 0.57546198, 0.3849309 ])

In [57]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])