<a href="https://colab.research.google.com/github/surajslab/NumpyBasics/blob/main/QuestionsNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# **Q1**
With your high school reunion fast approaching, you decide to get in shape and lose some weight. You record your weight every day for five weeks starting on a Monday. Given these daily weights, build an array with your average weight per weekend(saturday and sunday).



In [ ]:
weights= 185-np.arange(5*7)/5
weights

array([185. , 184.8, 184.6, 184.4, 184.2, 184. , 183.8, 183.6, 183.4,
       183.2, 183. , 182.8, 182.6, 182.4, 182.2, 182. , 181.8, 181.6,
       181.4, 181.2, 181. , 180.8, 180.6, 180.4, 180.2, 180. , 179.8,
       179.6, 179.4, 179.2, 179. , 178.8, 178.6, 178.4, 178.2])

## Solution

In [ ]:
(weights[5::7]+weights[6::7])/2

array([183.9, 182.5, 181.1, 179.7, 178.3])

# **Q2**
After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner. You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?

In [ ]:
import numpy as np

np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))
print(gold)

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]


In [ ]:
locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

## Solution

In [ ]:
gold[[0,2,2,5,6],[4,2,3,1,3]]

array([2, 6, 2, 8, 2])

In [ ]:
gold[locs[:,0],locs[:,1]]

array([2, 6, 2, 8, 2])

# **Q3**

You decide to invest in a series of billboards along interstate 10 to advertise your stylish new chicken restaurant, Chic-fil-A. You buy three billboards evenly spaced starting from mile marker 17 and ending on mile marker 28. Then you buy another three billboards starting on mile marker 32 and ending on mile marker 36. In order, from mile marker 17 to 36, your billboards display these ads: A, B, C, C, B, A. Determine how far each C ad is from your restaurant which is located at mile marker 30.



## Solution

In [28]:
np.linspace(17,28,3)

array([17. , 22.5, 28. ])

In [ ]:
np.linspace(32,36,3)

array([32., 34., 36.])

In [ ]:
np.linspace([17,32],[28,36],3,axis=1)

array([[17. , 22.5, 28. ],
       [32. , 34. , 36. ]])

Final solution

In [ ]:
np.abs(np.linspace([17,32],[28,36],3,axis=1)-30)[[0,1],[2,0]]

array([2., 2.])

# **Q4**

You’re a relationship scientist and you’ve developed a questionnaire that determines a person’s love score, a real-valued number between 0 and 100. Your theory is that two people with similar love scores should make a good match. Given the love scores for 10 different people, create a matrix where (i,j) gives the absolute difference of the love scores for person i and person j.

In [ ]:
import numpy as np

generator = np.random.default_rng(1010)
love_scores = np.round(generator.uniform(low=0, high=100, size=10), 2)
love_scores

array([ 9.5 , 53.58, 91.77, 98.15, 84.88, 74.61, 40.94, 56.49,  8.39,
       64.69])

## Solution

In [ ]:
love_scores.shape

(10,)

In [ ]:
love_scores[:,np.newaxis].shape

(10, 1)

In [ ]:
love_scores[np.newaxis].shape

(1, 10)

In [ ]:
print(abs(love_scores[:,np.newaxis]-love_scores[np.newaxis]))

[[ 0.   44.08 82.27 88.65 75.38 65.11 31.44 46.99  1.11 55.19]
 [44.08  0.   38.19 44.57 31.3  21.03 12.64  2.91 45.19 11.11]
 [82.27 38.19  0.    6.38  6.89 17.16 50.83 35.28 83.38 27.08]
 [88.65 44.57  6.38  0.   13.27 23.54 57.21 41.66 89.76 33.46]
 [75.38 31.3   6.89 13.27  0.   10.27 43.94 28.39 76.49 20.19]
 [65.11 21.03 17.16 23.54 10.27  0.   33.67 18.12 66.22  9.92]
 [31.44 12.64 50.83 57.21 43.94 33.67  0.   15.55 32.55 23.75]
 [46.99  2.91 35.28 41.66 28.39 18.12 15.55  0.   48.1   8.2 ]
 [ 1.11 45.19 83.38 89.76 76.49 66.22 32.55 48.1   0.   56.3 ]
 [55.19 11.11 27.08 33.46 20.19  9.92 23.75  8.2  56.3   0.  ]]


# **Q5**

You’re a vindictive, hateful professor and one of your pet peeves is when students rush through their exams. To teach them a lesson, you decide to give 0s to the first three students who score less than sixty, in the order they turned in their exams. So, given a 1d array of integers, identify the first three values less than sixty and replace them with zero.

In [2]:
import numpy as np

generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(low=30, high=100, size=15))
print(scores)


[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


## Solution

In [ ]:
scores[(scores<60).nonzero()[0][:3]]=0
scores

array([68.,  0., 76.,  0.,  0., 54., 63., 64., 36., 88., 80., 82., 84.,
       76., 42.])

# **Q6**

Eager to make your mark on the PTA, you decide the best way to hide eggs for for the upcoming Easter egg hunt is to use NumPy. You represent the field as a 10x10 array of 0s. Now your goal is to insert twenty random normal values at random (non repeating) locations in the grid that tell you how much candy to hide at each spot and where.

In [ ]:
import numpy as np

field = np.zeros(shape = (10, 10))
print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
field.size

100

## Solution


Creating 20 normal values

In [ ]:
generator= np.random.default_rng(seed=1234)
vals= np.round(generator.normal(size=20),2)


Creating 20 random locations

In [ ]:
locs=generator.choice(
    a=100,
    size=20,
    replace=False

)
locs

array([72, 96, 28, 37, 62, 73, 69, 17, 22, 44, 53, 21, 95,  0, 33, 82, 68,
       39, 83,  8])

To make it more dynamic

In [ ]:
locs=generator.choice(
    a=field.size,
    size=len(vals),
    replace=False

)
locs

array([15, 99, 42, 55, 41,  5,  3, 86, 39, 35, 61, 46, 63, 48, 11, 84, 24,
       17,  0, 51])

In [ ]:
np.ravel(field)[locs]=vals
print(field)

[[ 0.52  0.    0.   -1.48  0.    2.91  0.    0.    0.    0.  ]
 [ 0.   -1.27  0.    0.    0.   -1.6   0.    1.73  0.    0.  ]
 [ 0.    0.    0.    0.    0.43  0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.34  0.    0.    0.   -1.67]
 [ 0.    0.86  0.74  0.    0.    0.    1.32  0.    0.52  0.  ]
 [ 0.   -1.    0.    0.    0.    0.15  0.    0.    0.    0.  ]
 [ 0.   -0.51  0.   -0.86  0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.   -2.16  0.    0.95  0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.06]]


In [ ]:
import numpy as  np
arr= np.random.randint(1,7,size=(3,3))
arr

array([[1, 6, 1],
       [3, 6, 1],
       [3, 5, 2]])

# **Q7**

You’re given a 10x2 array of floats where each row represents a movie. The first column represents the movie’s rating and the second column represents the director’s rating. Your goal is to create a third column to represent the overall rating. The overall rating is equal to the movie rating if it exists, otherwise it’s the director’s rating.

In [ ]:
import numpy as np

generator = np.random.default_rng(123)
ratings = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
ratings[[1,2,7,9], [0,0,0,0]] = np.nan
print(ratings)

[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [ 5.  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [nan  5.]]


## Solution

In [ ]:
arr= np.where(np.isnan(ratings[:,0]), ratings[:,1], ratings[:,0])
np.concatenate((ratings,arr.reshape(10,1)),axis=1)

array([[ 7.,  1.,  7.],
       [nan,  2.,  2.],
       [nan,  8.,  8.],
       [ 9.,  3.,  9.],
       [ 8.,  9.,  8.],
       [ 5.,  2.,  5.],
       [ 8.,  2.,  8.],
       [nan,  6.,  6.],
       [ 9.,  2.,  9.],
       [nan,  5.,  5.]])

# **Q8**

10 fish occupy a 5x5x5 grid of water. Each fish decides to move to a new (i,j,k) location given by the matrix below. If multiple fish end up occupying the same cell, the biggest fish eats the smaller fish. Determine which fish will survive.

In [3]:

import numpy as np

locs = np.array([
    [0,0,0],
    [1,1,2],
    [0,0,0],
    [2,1,3],
    [5,5,4],
    [5,0,0],
    [5,0,0],
    [0,0,0],
    [2,1,3],
    [1,3,1]
])

In [10]:

generator = np.random.default_rng(1010)
weights = generator.normal(size=10)
print(weights)

[-1.69870017  0.53799701 -0.22561399 -1.09020894  0.55391264 -1.50115445
  0.44545933  1.3448172  -1.12364327  0.21216015]


##Solution

In [23]:
sorted_weights = np.argsort(weights)[::-1]


In [24]:
vals=locs[sorted_weights]

In [25]:
idx=np.unique(vals,axis=0,return_index=True)[1]

In [27]:
print(sorted_weights[idx])

[7 1 9 3 6 4]
